(function(highlight) {
    var themes = {}, 
	public = {
        PRE:'font-family:Monaco,Consolas,"Lucida Console","Courier New",serif;font-size:12px;line-height:20px; position: relative;*padding-bottom: 20px; cursor: text; overflow: hidden;width: auto; margin:10px auto; padding:10px;',
        BEFORE:"position:absolute; top:10px; right:10px;font-style: italic;font-size: 20px;z-index: -1;opacity: 0.4;filter:alpha(opacity=40); z-index:1;content: attr(data-language);",
        WARP:"white-space:pre-wrap;word-wrap:break-word;",
        OL_SPA:"Letter-spacing: 0.1px;",
        OL_LINE:"padding-left:40px;",
        OL_LIST:"display: list-item; padding-left:10px;list-style: decimal outside;"
    };
    themes.light = {
        public:public,
        main:"border:1px #CCC solid;background:#FFFFFF;color:#000066;",
        before:"color: goldenrod;",
        list:"border-left:#ddd solid 2px;",
        com:"color:#999;",
        mrk:"color:#00f; font-weight: bold;",
        vars:"color:#f0f;",
        key:"color:#009 ;font-weight: bold;",
        str:"color:#00f;",
        num:"color:#f00;",
        obj:"color:#099;",
        path:"color:#00f;",
        url:"color:#00f ; text-decoration:underline;",
        brt:"color:#000099;font-weight:bold;",
        ope:"color:#009;",
        attr:"color:#909;",
        reg:"color:#006600;",
        tag:"color:#00f;",
        bui:"color:#909;",
        slt:"color:#f0f;"
    }
	themes.gray = {
        public:public,
        main:"border:1px #CCC solid;background:#f9f9f9;color:#000066;",
        before:"color: goldenrod;",
        list:"border-left:#ddd solid 2px;",
        com:" color:#007400;",
        mrk:" color:#00f; font-weight: bold;",
        vars:" color:#0854FF;",
        key:" color:#AA0D91;;",
        str:" color:#C41A16;",
        num:" color:#f00;",
        obj:" color:#41AAB1;",
        path:" color:#C41A16 ;",
        url:" color:#C41A16 ; text-decoration:underline;",
        brt:" color:#000;font-weight:bold;",
        ope:" color:#009;",
        attr:" color:#909;",
        reg:" color:#f00;",
        tag:" color:#881280;",
        bui:" color:#DB00DB;",
        slt:"color:#f0f;"
    }
	themes.blue = {
        public:public,
        main:"background:#102144;color:#C7D4E2;",
        before:"color: #7A8994;",
        list:"border-left:#204187 solid 2px;",
        com:" color:#606C68;",
        mrk:" color: #EB03DF; font-weight: bold;",
        vars:" color:#8DFFFF;",
        key:" color:#8D8DFF ;font-weight: bold;",
        str:" color:#8CC21D;",
        num:" color:#05FFFF;",
        obj:" color:#63A7FF;",
        path:" color:#8CC21D ;",
        url:" color:#8CC21D ; text-decoration:underline;",
        brt:" color:#FFBD2E;font-weight:bold;",
        ope:" color:#FFAE00;",
        attr:" color:#D9684C;",
        reg:" color:#ff7d27;",
        tag:" color:#8D8DFF;",
        bui:" color:#EB03DF;",
        slt:"color:#EB03DF;"
    }
	themes.red = {
        public:public,
        main:"background:#240612;color:#FFEAEA;",
        before:"color: #7A8994;",
        list:"border-left:#5B0D2C solid 2px;",
        com:" color:#0056D0; background:#000;",
        mrk:" color: #EB03DF; font-weight: bold; ",
        vars:" color:#FD971F; ",
        key:" color:#DA1A6E ;font-weight: bold;",
        str:" color:#05D8FF ;background:#400A5E;",
        num:" color:#f00;",
        obj:" color:#A6E22E;",
        path:" color:#05D8FF ;background:#400A5E;",
        url:" color:#05D8FF ; background:#400A5E;",
        brt:" color:#FFBD2E;font-weight:bold;",
        ope:" color:#FFAE00;",
        attr:" color:#66D9EF;",
        reg:" color:#f00;background:#490612;",
        tag:" color:#FF0077;",
        bui:" color:#EB03DF;",
        slt:"color:#EB03DF;"
    }
	themes.dark = {
        public:public,
        main:"background:#394147;color:#fff;",
        before:"color: #7A8994;",
        list:"border-left:#546068 solid 2px;",
        com:" color:#3AE857; ",
        mrk:" color: #EB03DF; font-weight: bold; ",
        vars:" color:#f0f;",
        key:" color:#FFAE00 ;font-weight: bold;",
        str:" color:#05D8FF;",
        num:" color:#f00;",
        obj:" color:#A6E22E;",
        path:" color:#05D8FF ;",
        url:" color:#05D8FF ; text-decoration:underline;",
        brt:" color:#FFBD2E;font-weight:bold;",
        ope:" color:#FFAE00;",
        attr:" color:#ff0;",
        reg:" color:#ff7d27;",
        tag:" color:#FF0077;",
        bui:" color:#EB03DF;",
        slt:"color:#EB03DF;"
    };
	highlight.addOptions({themes:themes});
})(highlight);
